#!/usr/bin/env bash
# install nginx 
# Nginx should be listening on port 80
# return a page that contains the string Hello World!

# Updating and installing nginx
sudo apt-get update
sudo apt-get install nginx -y

# starting the nginx
sudo service nginx start

# setup to listen on port 80
sudo ufw allow 'Nginx HTTP'

# backup file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bkup

# giving ownership and mode
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html/*

# a page to return containing hello world
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restarting the nginx
sudo service nginx restart
