#!/usr/bin/env bash
# install and configuring haproxy to serve two web servers

sudo apt-get update
sudo apt-get install -y haproxy=2.9.\*

echo '
frontend bossjay.tech
	bind 0:80
	mode http
	default_backend web_server

backend web_server
	balance roundrobin
	server 526397-web-01 100.26.247.178:80 check
	server 526397-web-02 100.26.232.116:80 check
' >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
