#!/usr/bin/env bash
# install and configuring haproxy to serve two web servers

# installing
sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.9 -y
sudo apt-get -y install haproxy=2.9.\*

# configuration
echo '
frontend bossjay.tech
	bind 0:80
	mode http
	default_backend web_server

backend web_server
	balance roundrobin
	server 526397-web-01 54.162.76.183:80 check
	server 526397-web-02 35.174.176.235:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy
sudo service haproxy restart
