#!/usr/bin/env bash
# A bash script to configure nginx and listen on port 80
sudo apt-get update
sudo apt-get install nginx -y
sudo service nginx start
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
