#!/usr/bin/env bash
# A bash script that dispalys "To infinity and beyond" indefinitely
# With a 2-seconds sleep in between each iteration
# and
# I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
