#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd.
#The script displays only:
#username
#user id
#Home directory path for the user

list=$(cat /etc/passwd)
echo "$list"
