#!/usr/bin/env bash
# Nginx is running as the nginx user.
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available
pkill apache2
sudo -u nginx service nginx start
