#!/usr/bin/env bash
# uses ssh to connect to your server
# using the private key ~/.ssh/school
# with the user ubuntu

Private_key="~/.ssh/id_rsa"
user="ubuntu"
Server_address="54.208.157.253"

ssh -i "$Private_key" "$user@$Server_address"
